# Generated by Django 5.2.5 on 2025-08-31 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(\\+?61\\s?)?0?[2-9]\\d{8}$|^0[4-5]\\d{2}\\s?\\d{3}\\s?\\d{3}$', 'Please enter a valid Australian phone number (e.g., 0412 345 678 or +61 2 1234 5678)')], verbose_name='Guardian Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(\\+?61\\s?)?0?[2-9]\\d{8}$|^0[4-5]\\d{2}\\s?\\d{3}\\s?\\d{3}$', 'Please enter a valid Australian phone number (e.g., 0412 345 678 or +61 2 1234 5678)')], verbose_name='Phone Number'),
        ),
    ]
