# Generated by Django 5.2.5 on 2025-08-31 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_guardian_phone_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(0[4-5]\\d{2}\\s?\\d{3}\\s?\\d{3}|0[2,3,7-9]\\d?\\s?\\d{4}\\s?\\d{4}|0[2,3,7-9]\\d{8})$', 'Please enter a valid Australian phone number (e.g., 0412 345 678, 02 1234 5678)')], verbose_name='Guardian Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(0[4-5]\\d{2}\\s?\\d{3}\\s?\\d{3}|0[2,3,7-9]\\d?\\s?\\d{4}\\s?\\d{4}|0[2,3,7-9]\\d{8})$', 'Please enter a valid Australian phone number (e.g., 0412 345 678, 02 1234 5678)')], verbose_name='Phone Number'),
        ),
    ]
