# Generated by Django 5.2.5 on 2025-09-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_guardian_phone_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
                ('colour', models.CharField(default='#007bff', help_text='Hex colour code (e.g., #007bff)', max_length=7, verbose_name='Tag Colour')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Student Tag',
                'verbose_name_plural': 'Student Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='students', to='students.studenttag', verbose_name='Tags'),
        ),
    ]
