# Generated by Django 5.2.5 on 2025-09-04 01:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_enrollment_course_fee_enrollment_is_new_student_and_more'),
        ('students', '0005_studenttag_student_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(0[4-5]\\d{2}\\s?\\d{3}\\s?\\d{3}|0[2,3,7-9]\\d?\\s?\\d{4}\\s?\\d{4}|0[2,3,7-9]\\d{8})$', 'Please enter a valid Australian phone number (e.g., 0412 345 678, 02 1234 5678)')], verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_source',
            field=models.CharField(blank=True, help_text='Where/how the student enrolled', max_length=50, verbose_name='Enrollment Source'),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='System internal notes and history', verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any medical conditions we should be aware of', verbose_name='Medical Conditions'),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_contact_email',
            field=models.EmailField(blank=True, help_text='Main email address for course communications', max_length=254, verbose_name='Primary Contact Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_contact_phone',
            field=models.CharField(blank=True, help_text='Main phone number for SMS notifications', max_length=20, validators=[django.core.validators.RegexValidator('^(0[4-5]\\d{2}\\s?\\d{3}\\s?\\d{3}|0[2,3,7-9]\\d?\\s?\\d{4}\\s?\\d{4}|0[2,3,7-9]\\d{8})$', 'Please enter a valid Australian phone number (e.g., 0412 345 678, 02 1234 5678)')], verbose_name='Primary Contact Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_contact_type',
            field=models.CharField(choices=[('student', 'Student'), ('guardian', 'Guardian')], default='student', help_text='Indicates if primary contact is the student or guardian', max_length=20, verbose_name='Primary Contact Type'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_status',
            field=models.CharField(choices=[('new', 'New Student'), ('returning', 'Returning Student'), ('transferred', 'Transferred')], default='new', max_length=20, verbose_name='Registration Status'),
        ),
        migrations.AddField(
            model_name='student',
            name='source_enrollment',
            field=models.OneToOneField(blank=True, help_text='The enrollment record that created this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_student', to='enrollment.enrollment', verbose_name='Source Enrollment'),
        ),
        migrations.AddField(
            model_name='student',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Any special requirements or accommodations needed', verbose_name='Special Requirements'),
        ),
        migrations.AddField(
            model_name='student',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Internal notes for staff/teachers only', verbose_name='Staff Notes'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Student Personal Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(0[4-5]\\d{2}\\s?\\d{3}\\s?\\d{3}|0[2,3,7-9]\\d?\\s?\\d{4}\\s?\\d{4}|0[2,3,7-9]\\d{8})$', 'Please enter a valid Australian phone number (e.g., 0412 345 678, 02 1234 5678)')], verbose_name='Student Personal Phone'),
        ),
    ]
