# Generated by Django 5.2.5 on 2025-09-06 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_fix_registration_fee_nullable'),
        ('enrollment', '0002_enrollment_course_fee_enrollment_is_new_student_and_more'),
        ('students', '0006_student_emergency_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('enrollment_created', 'Enrollment Created'), ('enrollment_confirmed', 'Enrollment Confirmed'), ('enrollment_cancelled', 'Enrollment Cancelled'), ('attendance_marked', 'Attendance Marked'), ('payment_received', 'Payment Received'), ('course_completed', 'Course Completed'), ('contact_updated', 'Contact Information Updated'), ('notes_added', 'Staff Notes Added'), ('email_sent', 'Email Sent'), ('sms_sent', 'SMS Sent'), ('other', 'Other Activity')], max_length=30, verbose_name='Activity Type')),
                ('title', models.CharField(help_text='Brief description of the activity', max_length=200, verbose_name='Activity Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity', verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='JSON field for storing additional activity-specific data', verbose_name='Additional Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_visible_to_student', models.BooleanField(default=True, help_text='Whether this activity should be visible in student portal', verbose_name='Visible to Student/Guardian')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_activities', to='academics.course', verbose_name='Related Course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='enrollment.enrollment', verbose_name='Related Enrollment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Activity',
                'verbose_name_plural': 'Student Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='students_st_student_09754e_idx'), models.Index(fields=['activity_type', '-created_at'], name='students_st_activit_f19df7_idx')],
            },
        ),
    ]
