# Generated by Django 5.2.5 on 2025-09-09 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='primary_contact_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='primary_contact_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='primary_contact_type',
        ),
        migrations.AddField(
            model_name='student',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary email address for communications (student or guardian depending on age)', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary phone number for SMS notifications (student or guardian depending on age)', max_length=20, validators=[django.core.validators.RegexValidator('^(0[4-5]\\d{2}\\s?\\d{3}\\s?\\d{3}|0[2,3,7-9]\\d?\\s?\\d{4}\\s?\\d{4}|0[2,3,7-9]\\d{8})$', 'Please enter a valid Australian phone number (e.g., 0412 345 678, 02 1234 5678)')], verbose_name='Contact Phone'),
        ),
    ]
