# Generated by Django 5.2.5 on 2025-09-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_update_contact_fields'),
    ]

    operations = [
        # Remove registration_status field from Student model
        # This field has been migrated to Enrollment model for better business logic
        migrations.RemoveField(
            model_name='student',
            name='registration_status',
        ),
    ]
