# Generated by Django 5.2.5 on 2025-09-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20250916_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the level (e.g., Beginner, Intermediate, Advanced)', max_length=50, unique=True, verbose_name='Level Name')),
                ('order', models.PositiveIntegerField(help_text='Order in which levels should be displayed (lower numbers first)', verbose_name='Display Order')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this level represents', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this level is available for selection', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Student Level',
                'verbose_name_plural': 'Student Levels',
                'ordering': ['order', 'name'],
                'unique_together': {('order',)},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Current skill level of the student', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.studentlevel', verbose_name='Student Level'),
        ),
    ]
