# Generated by Django 5.2.5 on 2025-09-18 16:19

from django.db import migrations


def create_default_levels(apps, schema_editor):
    """Create default student levels"""
    StudentLevel = apps.get_model('students', 'StudentLevel')

    default_levels = [
        {'name': 'Beginner', 'order': 1, 'description': 'New students with little to no experience'},
        {'name': 'Intermediate', 'order': 2, 'description': 'Students with some experience and basic skills'},
        {'name': 'Advanced', 'order': 3, 'description': 'Experienced students with strong foundational skills'},
    ]

    for level_data in default_levels:
        StudentLevel.objects.get_or_create(
            name=level_data['name'],
            defaults={
                'order': level_data['order'],
                'description': level_data['description'],
                'is_active': True
            }
        )


def remove_default_levels(apps, schema_editor):
    """Remove default student levels (reverse migration)"""
    StudentLevel = apps.get_model('students', 'StudentLevel')

    default_level_names = ['Beginner', 'Intermediate', 'Advanced']
    StudentLevel.objects.filter(name__in=default_level_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentlevel_student_level'),
    ]

    operations = [
        migrations.RunPython(create_default_levels, remove_default_levels),
    ]
