# Generated by Django 5.2.5 on 2025-09-01 02:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('recipient_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('guardian', 'Guardian')], max_length=20, verbose_name='Recipient Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Email Subject')),
                ('content', models.TextField(verbose_name='Email Content')),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('enrollment_confirm', 'Enrolment Confirmation'), ('attendance_notice', 'Attendance Notice'), ('course_reminder', 'Course Reminder')], max_length=30, verbose_name='Email Type')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20, verbose_name='Send Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Send Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Recipient Phone')),
                ('recipient_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('guardian', 'Guardian')], max_length=20, verbose_name='Recipient Type')),
                ('content', models.TextField(verbose_name='SMS Content')),
                ('sms_type', models.CharField(choices=[('welcome', 'Welcome SMS'), ('enrollment_confirm', 'Enrolment Confirmation'), ('attendance_notice', 'Attendance Notice'), ('course_reminder', 'Course Reminder')], max_length=30, verbose_name='SMS Type')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20, verbose_name='Send Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Send Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClockInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out')], max_length=20, verbose_name='Clock Status')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Clock Time')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_records', to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Clock Record',
                'verbose_name_plural': 'Clock Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend_type', models.CharField(choices=[('google_workspace', 'Google Workspace'), ('aws_ses', 'Amazon SES'), ('custom_smtp', 'Custom SMTP')], default='google_workspace', max_length=20, verbose_name='Email Service Type')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_username', models.EmailField(max_length=254, verbose_name='SMTP Username/Email')),
                ('smtp_password', models.CharField(help_text='For Google Workspace, use App Password (not account password)', max_length=255, verbose_name='SMTP Password/App Password')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS Encryption')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Default From Email')),
                ('from_name', models.CharField(default='Perth Art School', max_length=100, verbose_name='Default From Name')),
                ('is_active', models.BooleanField(default=False, help_text='Only one configuration can be active at a time', verbose_name='Enable This Configuration')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Connection Test')),
                ('test_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending Test')], default='pending', max_length=20, verbose_name='Test Status')),
                ('test_message', models.TextField(blank=True, verbose_name='Test Result Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
    ]
