# Generated by Django 5.2.5 on 2025-08-24 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for WooCommerce listing', max_length=500, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Only published courses sync to WooCommerce', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom', verbose_name='Classroom'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('group', 'Group Class'), ('private', 'Private Lesson')], default='group', max_length=20, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank for single session courses', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='WooCommerce Product ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_bookable',
            field=models.BooleanField(default=True, verbose_name='Bookable'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='repeat_pattern',
            field=models.CharField(choices=[('once', 'Single Session'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20, verbose_name='Repeat Pattern'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='course',
            name='vacancy',
            field=models.PositiveIntegerField(default=1, verbose_name='Vacancy'),
        ),
    ]
