# Generated by Django 5.2.5 on 2025-09-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='email_backend',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Email Backend'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('welcome', 'Welcome Email'), ('enrollment_confirm', 'Enrolment Confirmation'), ('attendance_notice', 'Attendance Notice'), ('course_reminder', 'Course Reminder'), ('test', 'Test Email'), ('general', 'General Email')], max_length=30, verbose_name='Email Type'),
        ),
    ]
