# Generated by Django 5.2.5 on 2025-08-29 14:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_options_course_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterModelOptions(
            name='clockinout',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Clock Record', 'verbose_name_plural': 'Clock Records'},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Log', 'verbose_name_plural': 'Email Logs'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrolment', 'verbose_name_plural': 'Enrolments'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'SMS Log', 'verbose_name_plural': 'SMS Logs'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Attendance Time'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Record Time'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early_leave', 'Early Leave')], default='present', max_length=20, verbose_name='Attendance Status'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='class',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom', verbose_name='Classroom'),
        ),
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.DateField(verbose_name='Class Date'),
        ),
        migrations.AlterField(
            model_name='class',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='class',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.facility', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Classroom Name/Number'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='clockinout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='clockinout',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='clockinout',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='clockinout',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_records', to=settings.AUTH_USER_MODEL, verbose_name='Staff Member'),
        ),
        migrations.AlterField(
            model_name='clockinout',
            name='status',
            field=models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out')], max_length=20, verbose_name='Clock Status'),
        ),
        migrations.AlterField(
            model_name='clockinout',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Clock Time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='content',
            field=models.TextField(verbose_name='Email Content'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Send Time'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('welcome', 'Welcome Email'), ('enrollment_confirm', 'Enrolment Confirmation'), ('attendance_notice', 'Attendance Notice'), ('course_reminder', 'Course Reminder')], max_length=30, verbose_name='Email Type'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient_email',
            field=models.EmailField(max_length=254, verbose_name='Recipient Email'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('guardian', 'Guardian')], max_length=20, verbose_name='Recipient Type'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20, verbose_name='Send Status'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Email Subject'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enrolment Date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='form_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Form Data'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='source_channel',
            field=models.CharField(choices=[('website', 'Website'), ('form', 'Enrolment Form'), ('staff', 'Staff Member')], default='website', max_length=20, verbose_name='Enrolment Source'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Facility Name'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='content',
            field=models.TextField(verbose_name='SMS Content'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Send Time'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='recipient_phone',
            field=models.CharField(max_length=20, verbose_name='Recipient Phone'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='recipient_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('guardian', 'Guardian')], max_length=20, verbose_name='Recipient Type'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='sms_type',
            field=models.CharField(choices=[('welcome', 'Welcome SMS'), ('enrollment_confirm', 'Enrolment Confirmation'), ('attendance_notice', 'Attendance Notice'), ('course_reminder', 'Course Reminder')], max_length=30, verbose_name='SMS Type'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20, verbose_name='Send Status'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active_staff',
            field=models.BooleanField(default=True, verbose_name='Staff Status'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Please enter a valid phone number')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher')], default='teacher', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Guardian Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Guardian Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Please enter a valid phone number')], verbose_name='Guardian Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Please enter a valid phone number')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
