# Generated by Django 5.2.5 on 2025-09-01 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emaillog_email_backend_emaillog_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='backend_type',
            field=models.CharField(default='twilio', max_length=50, verbose_name='SMS Backend'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='message_sid',
            field=models.CharField(blank=True, help_text='Twilio message SID for tracking', max_length=50, verbose_name='Message SID'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='sms_type',
            field=models.CharField(choices=[('welcome', 'Welcome SMS'), ('enrollment_confirm', 'Enrolment Confirmation'), ('attendance_notice', 'Attendance Notice'), ('course_reminder', 'Course Reminder'), ('test', 'Test SMS'), ('general', 'General SMS')], max_length=30, verbose_name='SMS Type'),
        ),
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_backend_type', models.CharField(choices=[('twilio', 'Twilio SMS'), ('custom_sms', 'Custom SMS Gateway')], default='twilio', max_length=20, verbose_name='SMS Service Type')),
                ('account_sid', models.CharField(help_text='Twilio Account SID', max_length=255, verbose_name='Account SID')),
                ('auth_token', models.CharField(help_text='Twilio Auth Token', max_length=255, verbose_name='Auth Token')),
                ('from_number', models.CharField(help_text='Twilio phone number in E.164 format (e.g., +61400123456)', max_length=20, verbose_name='From Phone Number')),
                ('api_url', models.URLField(blank=True, help_text='Custom SMS gateway API endpoint', verbose_name='API URL')),
                ('api_key', models.CharField(blank=True, help_text='Custom SMS gateway API key', max_length=255, verbose_name='API Key')),
                ('sender_name', models.CharField(default='PerthArt', help_text='SMS sender name (max 11 characters for alphanumeric)', max_length=11, verbose_name='Sender Name')),
                ('is_active', models.BooleanField(default=False, help_text='Only one configuration can be active at a time', verbose_name='Enable This Configuration')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Connection Test')),
                ('test_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending Test')], default='pending', max_length=20, verbose_name='Test Status')),
                ('test_message', models.TextField(blank=True, verbose_name='Test Result Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'SMS Configuration',
                'verbose_name_plural': 'SMS Configurations',
            },
        ),
    ]
