# Generated by Django 5.2.5 on 2025-08-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attendance_options_alter_class_options_and_more'),
    ]

    operations = [
    ]
