# Generated by Django 5.2.5 on 2025-09-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_smslog_backend_type_smslog_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='reply_to_email',
            field=models.EmailField(blank=True, help_text='Email address for recipients to reply to. Leave blank to use from_email as reply-to', max_length=254, verbose_name='Reply-to Email Address'),
        ),
    ]
