# Generated by Django 5.2.5 on 2025-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailsettings_reply_to_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10, verbose_name='Notification Type')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Month')),
                ('monthly_limit', models.PositiveIntegerField(help_text='Maximum number of notifications allowed per month', verbose_name='Monthly Limit')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of notifications used this month', verbose_name='Used Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Quota',
                'verbose_name_plural': 'Notification Quotas',
                'ordering': ['-year', '-month', 'notification_type'],
                'unique_together': {('notification_type', 'year', 'month')},
            },
        ),
    ]
