# Generated by Django 5.2.5 on 2025-09-02 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_course_category'),
        ('core', '0005_notificationquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooCommerceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('create', 'Create Product'), ('update', 'Update Product'), ('delete', 'Delete Product'), ('category', 'Create/Update Category')], max_length=20, verbose_name='Sync Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20, verbose_name='Status')),
                ('course_name', models.CharField(blank=True, help_text='Cached course name for reference', max_length=200, verbose_name='Course Name')),
                ('wc_product_id', models.CharField(blank=True, max_length=100, verbose_name='WooCommerce Product ID')),
                ('wc_category_id', models.CharField(blank=True, max_length=100, verbose_name='WooCommerce Category ID')),
                ('wc_category_name', models.CharField(blank=True, max_length=200, verbose_name='WooCommerce Category Name')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Raw response from WooCommerce API', verbose_name='Response Data')),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Data sent to WooCommerce API', verbose_name='Request Data')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Time taken for the API call in milliseconds', null=True, verbose_name='Duration (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_attempt_at', models.DateTimeField(auto_now=True, verbose_name='Last Attempt At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='academics.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'WooCommerce Sync Log',
                'verbose_name_plural': 'WooCommerce Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WooCommerceSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sync', 'Sync Product'), ('delete', 'Delete Product'), ('category_sync', 'Sync Category')], max_length=20, verbose_name='Action')),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (3, 'High'), (5, 'Normal'), (7, 'Low'), (9, 'Background')], default=5, verbose_name='Priority')),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Scheduled For')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20, verbose_name='Status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Attempts')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('last_error', models.TextField(blank=True, verbose_name='Last Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue_items', to='academics.course', verbose_name='Course')),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.woocommercesynclog', verbose_name='Related Sync Log')),
            ],
            options={
                'verbose_name': 'WooCommerce Sync Queue Item',
                'verbose_name_plural': 'WooCommerce Sync Queue',
                'ordering': ['priority', 'scheduled_for'],
            },
        ),
        migrations.AddIndex(
            model_name='woocommercesynclog',
            index=models.Index(fields=['status', 'created_at'], name='core_woocom_status_012d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommercesynclog',
            index=models.Index(fields=['course', 'sync_type'], name='core_woocom_course__3e3546_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommercesynclog',
            index=models.Index(fields=['wc_product_id'], name='core_woocom_wc_prod_ea805c_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommercesyncqueue',
            index=models.Index(fields=['status', 'priority', 'scheduled_for'], name='core_woocom_status_a9a38d_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommercesyncqueue',
            index=models.Index(fields=['course', 'action'], name='core_woocom_course__2f6620_idx'),
        ),
    ]
