# Generated by Django 5.2.5 on 2025-09-04 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_fix_registration_fee_nullable'),
        ('core', '0006_woocommercesynclog_woocommercesyncqueue_and_more'),
        ('facilities', '0002_facility_attendance_radius_facility_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_type', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out')], max_length=20, verbose_name='Clock Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Clock Time')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='GPS latitude where teacher clocked in/out', max_digits=10, verbose_name='Teacher Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, help_text='GPS longitude where teacher clocked in/out', max_digits=11, verbose_name='Teacher Longitude')),
                ('distance_from_facility', models.FloatField(help_text='Calculated distance from facility location', verbose_name='Distance from Facility (meters)')),
                ('location_verified', models.BooleanField(default=False, help_text='Whether location is within acceptable range', verbose_name='Location Verified')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', verbose_name='User Agent')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('classes', models.ManyToManyField(blank=True, help_text='Classes that this attendance record is for', to='academics.class', verbose_name='Associated Classes')),
                ('facility', models.ForeignKey(help_text='Facility where attendance was recorded', on_delete=django.db.models.deletion.CASCADE, to='facilities.facility', verbose_name='Facility')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendance Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
