# Generated by Django 5.2.5 on 2025-09-08 04:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teacherattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(default='Perth Art School', max_length=200, verbose_name='Organisation Name')),
                ('abn_number', models.CharField(blank=True, help_text='Australian Business Number', max_length=20, verbose_name='ABN Number')),
                ('prices_include_gst', models.BooleanField(default=True, help_text='When enabled, all displayed prices include GST (10%). When disabled, GST will be added to displayed prices.', verbose_name='Prices Include GST')),
                ('gst_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), help_text='GST rate as decimal (e.g., 0.1000 for 10%)', max_digits=5, verbose_name='GST Rate')),
                ('show_gst_breakdown', models.BooleanField(default=True, help_text='Display detailed GST breakdown in prices and confirmations', verbose_name='Show GST Breakdown')),
                ('gst_label', models.CharField(default='GST', help_text='Label to use for GST (e.g., "GST", "Tax")', max_length=50, verbose_name='GST Label')),
                ('contact_email', models.EmailField(default='info@perthartschool.com.au', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(default='(08) 9000 0000', max_length=20, verbose_name='Contact Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Organisation Setting',
                'verbose_name_plural': 'Organisation Settings',
            },
        ),
    ]
