# Generated by Django 5.2.5 on 2025-09-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organisationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsettings',
            name='reply_to_email',
            field=models.EmailField(default='info@perthartschool.com.au', help_text='Default email address for recipients to reply to. Used when no specific reply-to is configured in email settings.', max_length=254, verbose_name='Reply-to Email Address'),
        ),
    ]
