# Generated by Django 5.2.5 on 2025-09-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organisationsettings_reply_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsettings',
            name='bank_account_name',
            field=models.CharField(default='Perth Art School Pty Ltd', help_text='Account name for bank transfers', max_length=100, verbose_name='Bank Account Name'),
        ),
        migrations.AddField(
            model_name='organisationsettings',
            name='bank_account_number',
            field=models.CharField(default='123456789', help_text='Bank account number for payments', max_length=20, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='organisationsettings',
            name='bank_bsb',
            field=models.CharField(default='036-032', help_text='Bank State Branch number (format: XXX-XXX)', max_length=7, verbose_name='BSB'),
        ),
        migrations.AddField(
            model_name='organisationsettings',
            name='site_domain',
            field=models.CharField(default='perthartschool.com.au', help_text='Primary website domain (without https://)', max_length=100, verbose_name='Website Domain'),
        ),
    ]
