# Generated by Django 5.2.5 on 2026-04-05 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_teacherattendance_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_attendance_created_records', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='manual_reason',
            field=models.TextField(blank=True, help_text='Reason provided when the record was entered manually', verbose_name='Manual Reason'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='source',
            field=models.CharField(choices=[('gps', 'GPS Clock'), ('qr', 'QR Clock'), ('manual', 'Manual Entry')], default='gps', max_length=20, verbose_name='Record Source'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_attendance_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='distance_from_facility',
            field=models.FloatField(blank=True, help_text='Calculated distance from facility location', null=True, verbose_name='Distance from Facility (meters)'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='GPS latitude where teacher clocked in/out', max_digits=10, null=True, verbose_name='Teacher Latitude'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='GPS longitude where teacher clocked in/out', max_digits=11, null=True, verbose_name='Teacher Longitude'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Clock Time'),
        ),
    ]
