# Generated by Django 5.2.5 on 2026-04-05 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_teacherattendance_created_by_and_more'),
        ('facilities', '0003_alter_facility_attendance_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility where attendance was recorded, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility', verbose_name='Facility'),
        ),
    ]
