# Generated by Django 5.2.5 on 2025-09-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='attendance_radius',
            field=models.PositiveIntegerField(default=100, help_text='Maximum distance in meters for valid attendance check-in', verbose_name='Attendance Verification Radius (meters)'),
        ),
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='GPS latitude coordinate for attendance verification', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='GPS longitude coordinate for attendance verification', max_digits=11, null=True, verbose_name='Longitude'),
        ),
    ]
