# Generated by Django 5.2.5 on 2025-09-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_attendance_radius_facility_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='attendance_radius',
            field=models.PositiveIntegerField(default=50, help_text='Maximum distance in meters for valid attendance check-in', verbose_name='Attendance Verification Radius (meters)'),
        ),
    ]
