# Generated by Django 5.2.5 on 2026-09-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_attendance_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='attendance_radius',
            field=models.PositiveIntegerField(default=100, help_text='Maximum distance in meters for valid attendance check-in', verbose_name='Attendance Verification Radius (meters)'),
        ),
    ]
