"""
Django settings for edupulse project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# 加载环境变量
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# It is recommended to set this in your environment variables for production.
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-c@=gl@5kfa53m#+pq-_=ih_-hy@ac)-1b0wmamj3fzw02s-ekw')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG = False in your production environment.
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Define allowed hosts. For production, set this to your domain name in environment variables.
# e.g., ALLOWED_HOSTS=edupulse.perthartschool.com.au
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')

# Site domain configuration for URL generation
# In development: SITE_DOMAIN=localhost:8000
# In production: SITE_DOMAIN=edupulse.perthartschool.com.au
SITE_DOMAIN = os.getenv('SITE_DOMAIN', 'localhost:8000')
SITE_PROTOCOL = os.getenv('SITE_PROTOCOL', 'https' if not DEBUG else 'http')


# Production security settings
# These settings are activated when DEBUG = False
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True

    # HSTS (HTTP Strict Transport Security) settings
    # Before enabling, ensure the entire site is served over HTTPS, or it will be inaccessible.
    # Start with a small value (e.g., 3600 for 1 hour) for testing.
    SECURE_HSTS_SECONDS = 2592000  # 30 days
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # Third-party applications
    'tinymce',
    'django_crontab',
    'django_rq',
    # Local applications - modular architecture
    'core',
    'accounts',
    'students',
    'academics',
    'facilities',
    'enrollment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edupulse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edupulse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalisation settings
LANGUAGE_CODE = 'en-au'  # Australian English

TIME_ZONE = 'Australia/Perth'  # Perth timezone

USE_I18N = True

USE_TZ = True


# 静态文件配置
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# DigitalOcean Spaces / S3-compatible storage configuration
IS_DEVELOPMENT = DEBUG  # Use DEBUG flag to determine environment
USE_DO_SPACES = os.getenv('USE_DO_SPACES', 'False' if IS_DEVELOPMENT else 'True') == 'True'

if USE_DO_SPACES:
    # Add storages to installed apps
    if 'storages' not in INSTALLED_APPS:
        INSTALLED_APPS.append('storages')
    
    # DigitalOcean Spaces configuration
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'sgp1')
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # 1 day cache
    }
    AWS_LOCATION = 'media'
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False  # Don't add auth query params to URLs
    
    # Use DO Spaces for default file storage (Django 5+: use STORAGES instead of only DEFAULT_FILE_STORAGE)
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    
    # Update MEDIA_URL to use DO Spaces
    # Build MEDIA_URL without duplicating the bucket if endpoint already includes it
    _endpoint = (AWS_S3_ENDPOINT_URL or '').rstrip('/')
    _bucket = AWS_STORAGE_BUCKET_NAME
    _base_media_url = _endpoint if _bucket in _endpoint else f"{_endpoint}/{_bucket}"
    MEDIA_URL = f'{_base_media_url}/{AWS_LOCATION}/'
    
    print(f"📦 Using DigitalOcean Spaces for media storage: {AWS_STORAGE_BUCKET_NAME}")
else:
    # Development - use local file storage
    print("📁 Using local file storage for development")


# 默认主键字段类型
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Caching configuration for progress tracking
# Use shared Redis cache when available so multi-worker progress polling stays consistent.
REDIS_CACHE_URL = os.getenv('REDIS_CACHE_URL') or os.getenv('REDIS_URL')
DEFAULT_CACHE_TIMEOUT = int(os.getenv('CACHE_DEFAULT_TIMEOUT', '300'))

# If no explicit Redis URL is provided, build one from host/port/db so production
# always uses a shared Redis cache instead of per-process in‑memory cache.
if not REDIS_CACHE_URL:
    redis_host_for_cache = os.getenv('REDIS_HOST', '127.0.0.1')
    redis_port_for_cache = os.getenv('REDIS_PORT', '6379')
    redis_db_for_cache = os.getenv('REDIS_DB', '0')
    REDIS_CACHE_URL = f"redis://{redis_host_for_cache}:{redis_port_for_cache}/{redis_db_for_cache}"

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'edupulse-cache',
    },
    'notifications': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_CACHE_URL,
        'TIMEOUT': DEFAULT_CACHE_TIMEOUT,
    },
}

# Redis / RQ queue settings for async notifications
REDIS_URL = os.getenv('REDIS_URL')
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', '6379'))
REDIS_DB = int(os.getenv('REDIS_DB', '0'))
RQ_DEFAULT_TIMEOUT = int(os.getenv('RQ_DEFAULT_TIMEOUT', '300'))
NOTIFICATION_QUEUE_TIMEOUT = int(os.getenv('NOTIFICATION_QUEUE_TIMEOUT', '600'))

_RQ_CONNECTION = (
    {'URL': REDIS_URL}
    if REDIS_URL
    else {
        'HOST': REDIS_HOST,
        'PORT': REDIS_PORT,
        'DB': REDIS_DB,
    }
)

RQ_QUEUES = {
    'default': {
        **_RQ_CONNECTION,
        'DEFAULT_TIMEOUT': RQ_DEFAULT_TIMEOUT,
    },
    'notifications': {
        **_RQ_CONNECTION,
        'DEFAULT_TIMEOUT': NOTIFICATION_QUEUE_TIMEOUT,
    },
}

# Email settings - Dynamic backend with environment variable fallback
EMAIL_BACKEND = 'core.backends.DynamicEmailBackend'
EMAIL_HOST = os.getenv('SMTP_SERVER', 'localhost')
SMTP_PORT_ENV = os.getenv('SMTP_PORT', '587')
EMAIL_PORT = int(SMTP_PORT_ENV)
EMAIL_HOST_USER = os.getenv('SMTP_USERNAME', '')
EMAIL_HOST_PASSWORD = os.getenv('SMTP_PASSWORD', '')
EMAIL_USE_SSL = (SMTP_PORT_ENV == '465') or (os.getenv('EMAIL_USE_SSL', 'False') == 'True')
EMAIL_USE_TLS = (not EMAIL_USE_SSL) and (os.getenv('EMAIL_USE_TLS', 'True') == 'True')
DEFAULT_FROM_EMAIL = os.getenv('SMTP_USERNAME', 'noreply@perthartschool.com.au')

# Email performance and reliability settings
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '60'))  # 60 seconds timeout
EMAIL_SSL_KEYFILE = None
EMAIL_SSL_CERTFILE = None

# Batch email settings for bulk operations
BULK_EMAIL_BATCH_SIZE = int(os.getenv('BULK_EMAIL_BATCH_SIZE', '20'))  # Send 20 emails per batch
BULK_EMAIL_BATCH_DELAY = float(os.getenv('BULK_EMAIL_BATCH_DELAY', '0'))  # 0 delay by default to avoid blocking

# Twilio 短信配置
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_FROM_NUMBER = os.getenv('TWILIO_FROM_NUMBER')

# 登录/登出重定向
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# Custom user model
AUTH_USER_MODEL = 'accounts.Staff'

# Sites framework
SITE_ID = 1

# TinyMCE 配置 - WordPress兼容的简化版本
TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': '100%',
    'menubar': False,  # 移除菜单栏避免混乱
    'branding': False,  # 移除"Powered by TinyMCE"
    'promotion': False,  # 移除升级按钮和广告
    'plugins': 'lists link image code help wordcount',
    'toolbar': 'undo redo | bold italic underline | bullist numlist | link image | code | help',
    'images_upload_url': '/core/tinymce/upload/',  # Custom upload endpoint
    'automatic_uploads': True,
    'images_reuse_filename': False,
    'file_picker_types': 'image',
    # WordPress兼容配置
    'forced_root_block': 'p',
    'force_br_newlines': False,
    'force_p_newlines': True,
    'convert_urls': False,  # 保持URL原样
    'paste_auto_cleanup_on_paste': True,
    'paste_remove_styles': True,
    'paste_remove_styles_if_webkit': True,
    'paste_strip_class_attributes': 'all',
    'custom_undo_redo_levels': 10,
}

# ===========================================
# Django-crontab Configuration
# ===========================================

CRONJOBS = [
    # Update expired courses daily at 2 AM
    ('0 2 * * *', 'django.core.management.call_command', ['update_expired_courses'], {
        'verbosity': 1,
    }),
    # Weekly status consistency check on Sundays at 3 AM
    ('0 3 * * 0', 'django.core.management.call_command', ['update_expired_courses', '--check-consistency'], {
        'verbosity': 1,
    }),
]

# Optional: Enable logging for cron jobs
CRONTAB_COMMAND_PREFIX = 'DJANGO_SETTINGS_MODULE=edupulse.settings'
