# Generated by Django 5.2.5 on 2025-08-31 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staff_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(\\+?61\\s?)?0?[2-9]\\d{8}$|^0[4-5]\\d{2}\\s?\\d{3}\\s?\\d{3}$|^0[4-5]\\d{8}$|^0[2,3,7-9]\\d{4}\\s?\\d{4}$|^0[2,3,7-9]\\d{8}$', 'Please enter a valid Australian phone number (e.g., 0412 345 678, 0412345678, 02 1234 5678)')], verbose_name='Phone Number'),
        ),
    ]
