# Generated by Django 5.2.5 on 2025-09-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee for the course at time of enrollment', max_digits=10, verbose_name='Course Fee'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_new_student',
            field=models.BooleanField(default=True, help_text='Whether student was new at time of enrollment', verbose_name='Is New Student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='matched_existing_student',
            field=models.BooleanField(default=False, help_text='Whether an existing student was matched during enrollment', verbose_name='Matched Existing Student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='original_form_data',
            field=models.JSONField(blank=True, help_text='Backup of original enrollment form data for audit purposes', null=True, verbose_name='Original Form Data'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Registration fee for new students', max_digits=10, verbose_name='Registration Fee'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='registration_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Registration Fee Paid'),
        ),
    ]
