# Generated by Django 5.2.5 on 2025-09-09 16:38

from django.db import migrations, models


def migrate_registration_status_forward(apps, schema_editor):
    """
    Migrate registration_status from Student to Enrollment
    """
    Enrollment = apps.get_model('enrollment', 'Enrollment')
    Student = apps.get_model('students', 'Student')
    
    # Get all enrollments and set registration_status based on student's status and enrollment order
    for enrollment in Enrollment.objects.all():
        student = enrollment.student
        
        # Get all enrollments for this student, ordered by creation date
        student_enrollments = Enrollment.objects.filter(
            student=student
        ).order_by('created_at')
        
        # Determine registration status based on enrollment order
        enrollment_index = list(student_enrollments.values_list('id', flat=True)).index(enrollment.id)
        
        if enrollment_index == 0:
            # First enrollment - use student's registration_status or default to 'new'
            enrollment.registration_status = getattr(student, 'registration_status', 'new')
        else:
            # Subsequent enrollments should be 'returning'
            enrollment.registration_status = 'returning'
        
        enrollment.save()
    
    print(f"Migrated registration_status for {Enrollment.objects.count()} enrollments")


def migrate_registration_status_reverse(apps, schema_editor):
    """
    Reverse migration - copy registration_status back to Student (if needed)
    """
    # This is a simplified reverse - in practice, we might want more complex logic
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_enrollment_course_fee_enrollment_is_new_student_and_more'),
        ('students', '0008_update_contact_fields'),  # Ensure student migrations are applied
    ]

    operations = [
        # Add the registration_status field to Enrollment
        migrations.AddField(
            model_name='enrollment',
            name='registration_status',
            field=models.CharField(
                choices=[
                    ('new', 'New Student'),
                    ('returning', 'Returning Student'),
                    ('transferred', 'Transferred Student')
                ],
                default='new',
                help_text='Student status for this specific enrollment',
                max_length=20,
                verbose_name='Registration Status'
            ),
        ),
        # Migrate data from Student.registration_status to Enrollment.registration_status
        migrations.RunPython(
            migrate_registration_status_forward,
            migrate_registration_status_reverse
        ),
    ]
