# Generated by Django 5.2.5 on 2025-09-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_fix_registration_fee_nullable'),
        ('enrollment', '0003_auto_20250910_0038'),
        ('students', '0009_auto_20250910_0057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_instance',
            field=models.ForeignKey(blank=True, help_text='Optional: specific class instance for this enrollment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.class', verbose_name='Class'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('class_instance__isnull', True)), fields=('student', 'course'), name='unique_student_course_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('class_instance__isnull', False)), fields=('student', 'class_instance'), name='unique_student_class_enrollment'),
        ),
    ]
