# Generated by Django 5.2.5 on 2025-09-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='early_bird_savings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount saved through early bird pricing', max_digits=10, null=True, verbose_name='Early Bird Savings'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_early_bird',
            field=models.BooleanField(default=False, help_text='Whether this enrollment received early bird pricing', verbose_name='Early Bird Enrollment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Regular course price before early bird discount', max_digits=10, null=True, verbose_name='Original Course Price'),
        ),
    ]
