# Generated by Django 5.2.5 on 2025-12-04 12:10

from django.db import migrations, models


def backfill_active_from(apps, schema_editor):
    Enrollment = apps.get_model('enrollment', 'Enrollment')
    updated = 0
    for enrollment in Enrollment.objects.filter(active_from__isnull=True):
        enrollment.active_from = enrollment.created_at
        enrollment.save(update_fields=['active_from'])
        updated += 1
    print(f"Backfilled active_from for {updated} enrollments")


def backfill_active_from_reverse(apps, schema_editor):
    Enrollment = apps.get_model('enrollment', 'Enrollment')
    Enrollment.objects.update(active_from=None)


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_enrollment_early_bird_savings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='active_from',
            field=models.DateTimeField(
                blank=True,
                help_text='Start datetime for this enrollment to apply to classes',
                null=True,
                verbose_name='Active From'
            ),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='active_until',
            field=models.DateTimeField(
                blank=True,
                help_text='End datetime (exclusive) for this enrollment to apply to classes',
                null=True,
                verbose_name='Active Until'
            ),
        ),
        migrations.RunPython(backfill_active_from, backfill_active_from_reverse),
    ]
