# Generated by Django 5.2.5 on 2026-01-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_enrollment_active_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early_leave', 'Early Leave'), ('unmarked', 'Unmarked')], default='unmarked', max_length=20, verbose_name='Attendance Status'),
        ),
    ]
