# Generated by Django 5.2.5 on 2026-02-07 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_course_status'),
        ('enrollment', '0007_alter_attendance_status'),
        ('students', '0012_auto_20250919_0019'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20, verbose_name='Status')),
                ('reason_type', models.CharField(choices=[('student_request', 'Student Request'), ('teacher_request', 'Teacher Request'), ('admin_adjustment', 'Admin Adjustment')], default='student_request', max_length=30, verbose_name='Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('initiated_from', models.CharField(choices=[('source', 'Source Class'), ('target', 'Target Class')], default='source', max_length=20, verbose_name='Initiated From')),
                ('snapshot_json', models.JSONField(blank=True, null=True, verbose_name='Audit Snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_sessions', to='academics.course', verbose_name='Source Course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_makeup_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('source_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_sessions_as_source', to='academics.class', verbose_name='Source Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_sessions', to='students.student', verbose_name='Student')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_sessions_as_target', to='academics.class', verbose_name='Target Class')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_makeup_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Makeup Session',
                'verbose_name_plural': 'Makeup Sessions',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_class', models.F('target_class')), _negated=True), name='makeup_source_target_must_differ'), models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('student', 'source_class', 'target_class'), name='unique_active_makeup_session')],
            },
        ),
    ]
