# Generated by Django 5.2.5 on 2025-08-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='repeat_day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of the month for monthly courses (1-31, auto-filled from start date)', null=True, verbose_name='Day of Month'),
        ),
        migrations.AddField(
            model_name='course',
            name='repeat_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week for weekly courses (auto-filled from start date)', null=True, verbose_name='Weekday'),
        ),
    ]
