# Generated by Django 5.2.5 on 2025-08-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_course_repeat_day_of_month_course_repeat_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bookable_state',
            field=models.CharField(choices=[('bookable', 'Bookable'), ('fully_booked', 'Fully Booked'), ('closed', 'Closed')], default='bookable', help_text='Current booking availability status', max_length=20, verbose_name='Bookable State'),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_deadline',
            field=models.DateField(blank=True, help_text='Last date to accept enrollments (leave blank for no deadline)', null=True, verbose_name='Enrollment Deadline'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('expired', 'Expired')], default='draft', help_text='Only published courses sync to WooCommerce', max_length=20, verbose_name='Status'),
        ),
    ]
