# Generated by Django 5.2.5 on 2025-08-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_add_course_status_and_enrollment_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_bookable',
        ),
        migrations.AddField(
            model_name='course',
            name='is_online_bookable',
            field=models.BooleanField(default=True, help_text='Enable students to enroll in this course through the online form', verbose_name='Allow Online Bookings'),
        ),
    ]
