# Generated by Django 5.2.5 on 2025-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_rename_is_bookable_and_remove_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('term_courses', 'Term Courses'), ('holiday_program', 'Holiday Program'), ('day_courses', 'Day Courses')], default='term_courses', help_text='Course category for organization and WooCommerce sync', max_length=20, verbose_name='Category'),
        ),
    ]
