# Generated by Django 5.2.5 on 2025-09-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image for course display and WooCommerce product', null=True, upload_to='course_images/%Y/%m/', verbose_name='Featured Image'),
        ),
    ]
