# Generated by Django 5.2.5 on 2025-09-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_course_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Additional fee for new student registration. Leave blank if no registration fee required.', max_digits=10, verbose_name='Registration Fee'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Course Fee'),
        ),
    ]
