# Generated by Django 5.2.5 on 2025-09-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_fix_registration_fee_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='repeat_pattern',
            field=models.CharField(choices=[('once', 'Single Session'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20, verbose_name='Repeat Pattern'),
        ),
    ]
