# Generated by Django 5.2.5 on 2025-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_course_repeat_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='daily_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Days of the week for daily courses (list of weekday numbers)', null=True, verbose_name='Daily Weekdays'),
        ),
    ]
