# Generated by Django 5.2.5 on 2025-09-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_add_daily_weekdays_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='early_bird_deadline',
            field=models.DateField(blank=True, help_text='Last date to enjoy early bird pricing. Must be before course start date.', null=True, verbose_name='Early Bird Deadline'),
        ),
        migrations.AddField(
            model_name='course',
            name='early_bird_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special price for early enrollments. Must be lower than regular course fee.', max_digits=10, null=True, verbose_name='Early Bird Price'),
        ),
    ]
