# Generated by Django 5.2.5 on 2025-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_course_early_bird_deadline_course_early_bird_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='woocommerce_last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='WooCommerce Last Synced At'),
        ),
    ]
