# Generated by Django 5.2.5 on 2026-01-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_course_woocommerce_last_synced_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', help_text='Only published courses sync to WooCommerce', max_length=20, verbose_name='Status'),
        ),
    ]
