# Generated by Django 5.2.5 on 2026-04-10 07:05

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Group Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Short Description')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Full Description')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='course_group_images/%Y/%m/', verbose_name='Featured Image')),
                ('category', models.CharField(choices=[('term_courses', 'Term Courses')], default='term_courses', max_length=20, verbose_name='Category')),
                ('course_type', models.CharField(choices=[('group', 'Group Class'), ('private', 'Private Lesson')], default='group', max_length=20, verbose_name='Course Type')),
                ('repeat_pattern', models.CharField(choices=[('weekly', 'Weekly')], default='weekly', max_length=20, verbose_name='Repeat Pattern')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Course Fee')),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Early Bird Price')),
                ('early_bird_deadline', models.DateField(blank=True, null=True, verbose_name='Early Bird Deadline')),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Registration Fee')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Course Group',
                'verbose_name_plural': 'Course Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.coursegroup', verbose_name='Course Group'),
        ),
    ]
